### ISSUE TITLE
SyntaxError: Unexpected token .

### ISSUE THREAD

**Issue by thE-iNviNciblE** [jcreigno/nodejs-mail-notifier#45]
/var/www/vhosts/chattet.de/maiwell-mail.chattet.de/node_modules/mail-notifier/index.js:117
2|simple-m | Notifier.prototype.dbg = function (...args) {
2|simple-m |                                    ^
2|simple-m | SyntaxError: Unexpected token .
2|simple-m |     at Module._compile (module.js:439:25)
2|simple-m |     at Object.Module._extensions..js (module.js:474:10)
2|simple-m |     at Module.load (module.js:356:32)
2|simple-m |     at Function.Module._load (module.js:312:12)
2|simple-m |     at Module.require (module.js:364:17)
2|simple-m |     at require (module.js:380:17)
2|simple-m |     at Object.<anonymous> (/var/www/vhosts/chattet.de/maiwell-mail.chattet.de/node_modules/mail-notifier/sample/simple-mail-notifier.js:1:78)
2|simple-m |     at Module._compile (module.js:456:26)
2|simple-m |     at Object.Module._extensions..js (module.js:474:10)
2|simple-m |     at Module.load (module.js:356:32)

**Comment by jcreigno** [comment]
A spread operator has been introduced by #31. You are having this issue on old version of node.
I've fixed it in master.
