### ISSUE TITLE
Encoding not recognized: 'UTF-32LE' 

### ISSUE THREAD

**Issue by Revadike** [jcreigno/nodejs-mail-notifier#56]
I'm getting these errors logged when receiving certain emails.
```
Error: Encoding not recognized: 'UTF-32LE' (searched as: 'utf32le')
    at Object.getCodec (.\node_modules\iconv-lite\lib\index.js:106:23)
    at Object.getDecoder (.\node_modules\iconv-lite\lib\index.js:127:23)
    at Object.decode (.\node_modules\iconv-lite\lib\index.js:40:25)
    at convertIconvLite (.\node_modules\encoding\lib\encoding.js:91:26)
    at convert (.\node_modules\encoding\lib\encoding.js:51:22)
    at Object.decodeBase64 (.\node_modules\mimelib\lib\mimelib.js:257:16)
    at Object.decodeMimeWord (.\node_modules\mimelib\lib\mimelib.js:330:25)
    at Object.module.exports.decodeMimeWord (.\node_modules\mimelib\lib\mimelib.js:64:41)
    at MailParser.<anonymous> (.\node_modules\mail-notifier\node_modules\mailparser\lib\mailparser.js:1395:24)
    at String.replace (<anonymous>)
```

**Comment by jcreigno** [comment]
UTF-32LE is not supported by node-iconv-lite which is used by mailparser.
https://github.com/ashtuchkin/iconv-lite/wiki/Supported-Encodings

**Comment by Revadike** [comment]
Any workarounds that can be applied?
